log4tango::Layout Class Reference
#include `Layout.hh`
Public Member Functions
Layout ()
Constructor for Layout.
virtual ~Layout ()
Destructor for Layout.
virtual std::string format (const LoggingEvent &event)
Formats the LoggingEvent data to a string that appenders can log.
Constructor & Destructor Documentation
log4tango::Layout::Layout () [inline]
Constructor for Layout.
virtual log4tango::Layout::~Layout () [inline], [virtual]
Destructor for Layout.
Member Function Documentation
std::string log4tango::Layout::format (const LoggingEvent & event) [virtual]
Formats the LoggingEvent data to a string that appenders can log.
Overload this method to create your own layout format.
Parameters
event The LoggingEvent.
Returns
an appendable string.
Reimplemented in log4tango::PatternLayout , and log4tango::XMLLayout .
References log4tango::Level::get_name(), log4tango::LoggingEvent::level, and std::ostringstream::str().
Referenced by log4tango::OstreamAppender::_append().
The documentation for this class was generated from the following files:
Layout.hh
Layout.cpp