log4tango::Appender Class Reference
#include `Appender.hh`
Public Member Functions
virtual ~Appender ()
Destructor for Appender.
int append (const LoggingEvent &event)
Log in Appender specific way.
virtual void close (void)=0
Release any resources allocated within the appender such as file handles, network connections, etc.
const std::string & get_name (void) const
Returns this appender name.
virtual bool is_valid (void) const
Check if the appender is valid (for instance the underlying connection is ok) This default implementation always return true.
virtual bool reopen (void)
Reopens the output destination of this Appender, e.g.
virtual bool requires_layout (void) const =0
Check if the appender uses a layout.
virtual void set_layout (Layout *layout=0)=0
Change the layout.
Protected Member Functions
Appender (const std::string &name)
Constructor for Appender.
virtual int _append (const LoggingEvent &event)=0
Log in Appender specific way.
virtual void level_changed (Level::Value new_level)
Inform an appender that its Logger's logging level has changed.
Friends
class Logger
Constructor & Destructor Documentation
log4tango::Appender::Appender (const std::string & name) [protected]
Constructor for Appender.
Will only be used in getAppender() (and in derived classes of course).
Parameters
name The name of this Appender.
log4tango::Appender::~Appender () [virtual]
Destructor for Appender.
Member Function Documentation
virtual int log4tango::Appender::_append (const LoggingEvent & event) [protected], [pure virtual]
Log in Appender specific way.
Subclasses of Appender should implement this method to perform actual logging.
Parameters
event The LoggingEvent to log.
Implemented in log4tango::FileAppender , log4tango::RollingFileAppender , and log4tango::OstreamAppender .
int log4tango::Appender::append (const LoggingEvent & event) [inline]
Log in Appender specific way.
Returns -1 on error, 0 otherwise.
Parameters
event The LoggingEvent to log.
virtual void log4tango::Appender::close (void) [pure virtual]
Release any resources allocated within the appender such as file handles, network connections, etc.
Implemented in log4tango::FileAppender , and log4tango::OstreamAppender .
const std::string& log4tango::Appender::get_name (void) const [inline]
Returns this appender name.
Referenced by log4tango::AppenderAttachable::add_appender(), log4tango::AppenderAttachable::is_attached(), and log4tango::AppenderAttachable::remove_appender().
bool log4tango::Appender::is_valid (void) const [virtual]
Check if the appender is valid (for instance the underlying connection is ok) This default implementation always return true.
Overload to define your own behaviour.
Returns
true if the appender is valid, false otherwise.
Reimplemented in log4tango::FileAppender .
void log4tango::Appender::level_changed (Level::Value new_level) [protected], [virtual]
Inform an appender that its Logger's logging level has changed.
The default implementation does nothing.
Parameters
new_level The new Logger's level.
bool log4tango::Appender::reopen (void) [virtual]
Reopens the output destination of this Appender, e.g.
the logfile or TCP socket.
Returns
false if an error occured during reopening, true otherwise.
Reimplemented in log4tango::FileAppender , and log4tango::OstreamAppender .
virtual bool log4tango::Appender::requires_layout (void) const [pure virtual]
Check if the appender uses a layout.
Returns
true if the appender implementation requires a layout.
Implemented in log4tango::LayoutAppender .
virtual void log4tango::Appender::set_layout (Layout * layout = 0) [pure virtual]
Change the layout.
Implemented in log4tango::LayoutAppender .
Friends And Related Function Documentation
friend class Logger [friend]
The documentation for this class was generated from the following files:
Appender.hh
Appender.cpp