std::ostringstream Class Reference
#include `Portability.hh`
Public Member Functions
std::string str ()
void str (const char *)
Member Function Documentation
std::string std::ostringstream::str ()
Referenced by log4tango::TimeStampComponent::append(), log4tango::FormatModifierComponent::append(), log4tango::LoggerStream::flush(), log4tango::Layout::format(), log4tango::PatternLayout::format(), log4tango::RollingFileAppender::roll_over(), and log4tango::PatternLayout::set_conversion_pattern().
void std::ostringstream::str (const char * s)
The documentation for this class was generated from the following files:
Portability.hh
PortabilityImpl.cpp