log4tango::threading::ScopedLock Class Reference
#include `MSThreads.hh`
Public Member Functions
ScopedLock (Mutex &m)
ScopedLock (Mutex &mutex)
~ScopedLock ()
~ScopedLock ()
Constructor & Destructor Documentation
log4tango::threading::ScopedLock::ScopedLock (Mutex & mutex) [inline]
References log4tango::threading::Mutex::get_critical_section().
log4tango::threading::ScopedLock::~ScopedLock () [inline]
log4tango::threading::ScopedLock::ScopedLock (Mutex & m) [inline]
References log4tango::threading::Mutex::lock().
log4tango::threading::ScopedLock::~ScopedLock () [inline]
References log4tango::threading::Mutex::unlock().
The documentation for this class was generated from the following files:
MSThreads.hh
PThreads.hh