log4tango::Logger Class Reference
#include `Logger.hh`
Public Member Functions
Logger (const std::string &name, Level::Value level=Level::OFF)
Constructor.
virtual ~Logger ()
Destructor.
void debug (const char *string_format,...)
Log a message with debug level.
void debug (const std::string &message)
Log a message with debug level.
LoggerStream debug_stream (void)
Return a LoggerStream with level DEBUG.
void error (const char *string_format,...)
Log a message with error level.
void error (const std::string &message)
Log a message with error level.
LoggerStream error_stream (void)
Return a LoggerStream with level ERROR.
void fatal (const char *string_format,...)
Log a message with fatal level.
void fatal (const std::string &message)
Log a message with fatal level.
LoggerStream fatal_stream (void)
Return a LoggerStream with level FATAL.
Level::Value get_level () const
Returns the assigned Level, if any, for this Logger.
const std::string & get_name () const
Return the logger name.
LoggerStream get_stream (Level::Value level, bool filter=true)
Return a LoggerStream with given Level.
void info (const char *string_format,...)
Log a message with info level.
void info (const std::string &message)
Log a message with info level.
LoggerStream info_stream (void)
Return a LoggerStream with level INFO.
bool is_debug_enabled (void) const
Return true if the Logger will log messages with level DEBUG.
bool is_error_enabled (void) const
Return true if the Logger will log messages with level ERROR.
bool is_fatal_enabled (void) const
Return true if the Logger will log messages with level FATAL.
bool is_info_enabled (void) const
Return true if the Logger will log messages with level INFO.
bool is_level_enabled (Level::Value level) const
Returns true if the level of the Logger is equal to or higher than given level.
bool is_warn_enabled (void) const
Return true if the Logger will log messages with level WARN.
void log (Level::Value level, const char *string_format,...)
Log a message with the specified level.
void log (Level::Value level, const std::string &message)
Log a message with the specified level.
void log_unconditionally (Level::Value level, const char *string_format,...)
Log a message with the specified level without level checking.
void log_unconditionally (Level::Value level, const std::string &message)
Log a message with the specified level without level checking.
void set_level (Level::Value level)
Set the level of this Logger (silently ignores invalid values)
void warn (const char *string_format,...)
Log a message with warn level.
void warn (const std::string &message)
Log a message with warn level.
LoggerStream warn_stream (void)
Return a LoggerStream with level WARN.
Protected Member Functions
void call_appenders (const LoggingEvent &event)
Call the appenders.
Additional Inherited Members
Constructor & Destructor Documentation
log4tango::Logger::Logger (const std::string & name, Level::Value level = Level::OFF)
Constructor.
Parameters
name the fully qualified name of this Logger
level the level for this Logger. Defaults to Level::OFF
References log4tango::Level::DEBUG, log4tango::Level::ERROR, log4tango::Level::FATAL, log4tango::Level::INFO, and log4tango::Level::WARN.
log4tango::Logger::~Logger () [virtual]
Destructor.
Member Function Documentation
void log4tango::Logger::call_appenders (const LoggingEvent & event) [protected]
Call the appenders.
Parameters
event the LogginEvent to log.
References log4tango::AppenderAttachable::_appenders, log4tango::AppenderAttachable::_appendersMutex, and log4tango::AppenderAttachable::remove_appender().
Referenced by log_unconditionally().
void log4tango::Logger::debug (const char * string_format, ...)
Log a message with debug level.
Parameters
string_format Format specifier for the log.
... The arguments for string_format
References log4tango::Level::DEBUG, is_level_enabled(), log_unconditionally(), and log4tango::StringUtil::vform().
void log4tango::Logger::debug (const std::string & message) [inline]
Log a message with debug level.
Parameters
message string to write in the log file
References log4tango::Level::DEBUG.
LoggerStream log4tango::Logger::debug_stream (void) [inline]
Return a LoggerStream with level DEBUG.
Returns
The LoggerStream.
References log4tango::Level::DEBUG.
void log4tango::Logger::error (const char * string_format, ...)
Log a message with error level.
Parameters
string_format Format specifier for the log.
... The arguments for string_format
References log4tango::Level::ERROR, is_level_enabled(), log_unconditionally(), and log4tango::StringUtil::vform().
void log4tango::Logger::error (const std::string & message) [inline]
Log a message with error level.
Parameters
message string to write in the log file
References log4tango::Level::ERROR.
LoggerStream log4tango::Logger::error_stream (void) [inline]
Return a LoggerStream with level ERROR.
Returns
The LoggerStream.
References log4tango::Level::ERROR.
void log4tango::Logger::fatal (const char * string_format, ...)
Log a message with fatal level.
Parameters
string_format Format specifier for the log.
... The arguments for string_format
References log4tango::Level::FATAL, is_level_enabled(), log_unconditionally(), and log4tango::StringUtil::vform().
void log4tango::Logger::fatal (const std::string & message) [inline]
Log a message with fatal level.
Parameters
message string to write in the log file
References log4tango::Level::FATAL.
LoggerStream log4tango::Logger::fatal_stream (void) [inline]
Return a LoggerStream with level FATAL.
Returns
The LoggerStream.
References log4tango::Level::FATAL.
Level::Value log4tango::Logger::get_level () const [inline]
Returns the assigned Level, if any, for this Logger.
Returns
Level - the assigned Level, can be Level::NOTSET
const std::string& log4tango::Logger::get_name (void) const [inline]
Return the logger name.
Returns
The logger name.
Referenced by log_unconditionally().
LoggerStream log4tango::Logger::get_stream (Level::Value level, bool filter = true) [inline]
Return a LoggerStream with given Level.
Parameters
level The Level of the LoggerStream.
filter The filter flag
Returns
The requested LoggerStream.
void log4tango::Logger::info (const char * string_format, ...)
Log a message with info level.
Parameters
string_format Format specifier for the log.
... The arguments for string_format
References log4tango::Level::INFO, is_level_enabled(), log_unconditionally(), and log4tango::StringUtil::vform().
void log4tango::Logger::info (const std::string & message) [inline]
Log a message with info level.
Parameters
message string to write in the log file
References log4tango::Level::INFO.
LoggerStream log4tango::Logger::info_stream (void) [inline]
Return a LoggerStream with level INFO.
Returns
The LoggerStream.
References log4tango::Level::INFO.
bool log4tango::Logger::is_debug_enabled (void) const [inline]
Return true if the Logger will log messages with level DEBUG.
Returns
Whether the Logger will log.
References log4tango::Level::DEBUG.
bool log4tango::Logger::is_error_enabled (void) const [inline]
Return true if the Logger will log messages with level ERROR.
Returns
Whether the Logger will log.
References log4tango::Level::ERROR.
bool log4tango::Logger::is_fatal_enabled (void) const [inline]
Return true if the Logger will log messages with level FATAL.
Returns
Whether the Logger will log.
References log4tango::Level::FATAL.
bool log4tango::Logger::is_info_enabled (void) const [inline]
Return true if the Logger will log messages with level INFO.
Returns
Whether the Logger will log.
References log4tango::Level::INFO.
bool log4tango::Logger::is_level_enabled (Level::Value level) const [inline]
Returns true if the level of the Logger is equal to or higher than given level.
Parameters
level The level to compare with.
Returns
whether logging is enable for this level.
Referenced by debug(), error(), fatal(), info(), log(), and warn().
bool log4tango::Logger::is_warn_enabled (void) const [inline]
Return true if the Logger will log messages with level WARN.
Returns
Whether the Logger will log.
References log4tango::Level::WARN.
void log4tango::Logger::log (Level::Value level, const char * string_format, ...)
Log a message with the specified level.
Parameters
level The level of this log message.
string_format Format specifier for the log .
... The arguments for string_format
References is_level_enabled(), log_unconditionally(), and log4tango::StringUtil::vform().
Referenced by log4tango::LoggerStream::flush().
void log4tango::Logger::log (Level::Value level, const std::string & message) [inline]
Log a message with the specified level.
Parameters
level The level of this log message.
message string to write in the log file
void log4tango::Logger::log_unconditionally (Level::Value level, const char * string_format, ...)
Log a message with the specified level without level checking.
Parameters
level The level of this log message.
string_format Format specifier for the log .
... The arguments for string_format
References log4tango::StringUtil::vform().
Referenced by debug(), error(), fatal(), log4tango::LoggerStream::flush(), info(), log(), and warn().
void log4tango::Logger::log_unconditionally (Level::Value level, const std::string & message)
Log a message with the specified level without level checking.
Parameters
level The level of this log message.
message string to write in the log file
References call_appenders(), and get_name().
void log4tango::Logger::set_level (Level::Value level)
Set the level of this Logger (silently ignores invalid values)
Parameters
level The level to set.
References log4tango::AppenderAttachable::_appenders, log4tango::AppenderAttachable::_appendersMutex, log4tango::Level::DEBUG, and log4tango::Level::OFF.
void log4tango::Logger::warn (const char * string_format, ...)
Log a message with warn level.
Parameters
string_format Format specifier for the log.
... The arguments for string_format
References is_level_enabled(), log_unconditionally(), log4tango::StringUtil::vform(), and log4tango::Level::WARN.
void log4tango::Logger::warn (const std::string & message) [inline]
Log a message with warn level.
Parameters
message string to write in the log file
References log4tango::Level::WARN.
LoggerStream log4tango::Logger::warn_stream (void) [inline]
Return a LoggerStream with level WARN.
Returns
The LoggerStream.
References log4tango::Level::WARN.
The documentation for this class was generated from the following files:
Logger.hh
Logger.cpp