log4tango::OstreamAppender Class Reference
#include `OstreamAppender.hh`
Public Member Functions
OstreamAppender (const std::string &name, std::ostream *stream)
virtual ~OstreamAppender ()
virtual void close ()
Release any resources allocated within the appender such as file handles, network connections, etc.
virtual bool reopen ()
Reopens the output destination of this Appender, e.g.
Protected Member Functions
virtual int _append (const LoggingEvent &event)
Log in Appender specific way.
Protected Attributes
std::ostream * _stream
Additional Inherited Members
Constructor & Destructor Documentation
log4tango::OstreamAppender::OstreamAppender (const std::string & name, std::ostream * stream)
log4tango::OstreamAppender::~OstreamAppender () [virtual]
References close().
Member Function Documentation
int log4tango::OstreamAppender::_append (const LoggingEvent & event) [protected], [virtual]
Log in Appender specific way.
Subclasses of Appender should implement this method to perform actual logging.
Parameters
event The LoggingEvent to log.
Implements log4tango::Appender .
References _stream, std::endl(), log4tango::Layout::format(), and log4tango::LayoutAppender::get_layout().
void log4tango::OstreamAppender::close () [virtual]
Release any resources allocated within the appender such as file handles, network connections, etc.
Implements log4tango::Appender .
Referenced by ~OstreamAppender().
bool log4tango::OstreamAppender::reopen (void) [virtual]
Reopens the output destination of this Appender, e.g.
the logfile or TCP socket.
Returns
false if an error occured during reopening, true otherwise.
Reimplemented from log4tango::Appender .
Member Data Documentation
std::ostream* log4tango::OstreamAppender::_stream [protected]
Referenced by _append().
The documentation for this class was generated from the following files:
OstreamAppender.hh
OstreamAppender.cpp