log4tango::TimeStamp Class Reference
#include `TimeStamp.hh`
Public Member Functions
TimeStamp ()
Constructs a TimeStamp representing 'now'.
TimeStamp (const TimeStamp &t)
Copy Constructor.
TimeStamp (unsigned int seconds, unsigned int microseconds=0)
Constructs a TimeStamp representing the given offset since the epoch (00:00:00 1970/1/1 UTC).
int get_microseconds (void) const
Returns the subsecond part of the TimeStamp in microseconds.
int get_milliseconds (void) const
Returns the 'subseconds' part of the TimeStamp in milliseconds, get_milliseconds() == get_microseconds() / 1000.
int get_seconds (void) const
Returns the 'seconds' part of the TimeStamp.
void operator= (const TimeStamp &t)
Operator=.
Static Public Member Functions
static const TimeStamp & get_start_time (void)
Returns a TimeStamp representing the time at which the application started.
Protected Attributes
int _micro_seconds
int _seconds
Static Protected Attributes
static TimeStamp _start_stamp
Constructor & Destructor Documentation
log4tango::TimeStamp::TimeStamp ()
Constructs a TimeStamp representing 'now'.
References _micro_seconds, and _seconds.
log4tango::TimeStamp::TimeStamp (const TimeStamp & t) [inline]
Copy Constructor.
log4tango::TimeStamp::TimeStamp (unsigned int seconds, unsigned int microseconds = 0) [inline]
Constructs a TimeStamp representing the given offset since the epoch (00:00:00 1970/1/1 UTC).
Member Function Documentation
int log4tango::TimeStamp::get_microseconds (void) const [inline]
Returns the subsecond part of the TimeStamp in microseconds.
The actual precision of this value depends on the platform and may be in the order of milliseconds rather than microseconds.
int log4tango::TimeStamp::get_milliseconds (void) const [inline]
Returns the 'subseconds' part of the TimeStamp in milliseconds, get_milliseconds() == get_microseconds() / 1000.
Referenced by log4tango::MillisSinceEpochComponent::append().
int log4tango::TimeStamp::get_seconds (void) const [inline]
Returns the 'seconds' part of the TimeStamp.
Referenced by log4tango::MillisSinceEpochComponent::append().
static const TimeStamp& log4tango::TimeStamp::get_start_time (void) [inline], [static]
Returns a TimeStamp representing the time at which the application started.
Referenced by log4tango::MillisSinceEpochComponent::append().
void log4tango::TimeStamp::operator= (const TimeStamp & t) [inline]
Operator=.
References _micro_seconds, and _seconds.
Member Data Documentation
int log4tango::TimeStamp::_micro_seconds [protected]
Referenced by operator=(), and TimeStamp().
int log4tango::TimeStamp::_seconds [protected]
Referenced by operator=(), and TimeStamp().
TimeStamp log4tango::TimeStamp::_start_stamp [static], [protected]
The documentation for this class was generated from the following files:
TimeStamp.hh
TimeStamp.cpp