log4tango::threading::Mutex Class Reference
#include `MSThreads.hh`
Public Member Functions
Mutex ()
Mutex ()
~Mutex ()
~Mutex ()
LPCRITICAL_SECTION get_critical_section (void)
void lock ()
void unlock ()
Constructor & Destructor Documentation
log4tango::threading::Mutex::Mutex () [inline]
log4tango::threading::Mutex::~Mutex () [inline]
log4tango::threading::Mutex::Mutex () [inline]
log4tango::threading::Mutex::~Mutex () [inline]
Member Function Documentation
LPCRITICAL_SECTION log4tango::threading::Mutex::get_critical_section (void) [inline]
Referenced by log4tango::threading::ScopedLock::ScopedLock().
void log4tango::threading::Mutex::lock () [inline]
Referenced by log4tango::threading::ScopedLock::ScopedLock().
void log4tango::threading::Mutex::unlock (void) [inline]
Referenced by log4tango::threading::ScopedLock::~ScopedLock().
The documentation for this class was generated from the following files:
MSThreads.hh
PThreads.hh