log4tango::MillisSinceEpochComponent Struct Reference
Public Member Functions
virtual void append (std::ostringstream &out, const LoggingEvent &event)
Member Function Documentation
virtual void log4tango::MillisSinceEpochComponent::append (std::ostringstream & out, const LoggingEvent & event) [inline], [virtual]
Implements log4tango::PatternLayout::PatternComponent .
References log4tango::TimeStamp::get_milliseconds(), log4tango::TimeStamp::get_seconds(), and log4tango::TimeStamp::get_start_time().
The documentation for this struct was generated from the following file:
PatternLayout.cpp