log4tango::PatternLayout Class Reference
#include `PatternLayout.hh`
Classes
class PatternComponent
Public Member Functions
PatternLayout ()
virtual ~PatternLayout ()
virtual void clear_conversion_pattern ()
virtual std::string format (const LoggingEvent &event)
Formats the LoggingEvent in the style set by the set_conversion_pattern call.
virtual std::string get_conversion_pattern () const
virtual int set_conversion_pattern (const std::string &conversionPattern)
Sets the format of log lines handled by this PatternLayout.
Static Public Attributes
static const char * BASIC_CONVERSION_PATTERN = `%R %p %c %m%n`
A conversion pattern equivalent to the BasicLayout.
Constructor & Destructor Documentation
log4tango::PatternLayout::PatternLayout ()
References BASIC_CONVERSION_PATTERN, and set_conversion_pattern().
log4tango::PatternLayout::~PatternLayout () [virtual]
References clear_conversion_pattern().
Member Function Documentation
void log4tango::PatternLayout::clear_conversion_pattern () [virtual]
Referenced by set_conversion_pattern(), and ~PatternLayout().
std::string log4tango::PatternLayout::format (const LoggingEvent & event) [virtual]
Formats the LoggingEvent in the style set by the set_conversion_pattern call.
By default, set to `%%m%%n`
Reimplemented from log4tango::Layout .
References std::ostringstream::str().
std::string log4tango::PatternLayout::get_conversion_pattern () const [virtual]
int log4tango::PatternLayout::set_conversion_pattern (const std::string & conversionPattern) [virtual]
Sets the format of log lines handled by this PatternLayout.
By default, set to `%%m%%n`.
 Format characters are as follows:
%%%% - a single percent sign
%c - the logger
%d - the date
 Date format: The date format character may be followed by a date format specifier enclosed between braces. For example, %d{%H:%M:%S,%l} or %d{%d %m %Y %H:%M:%S,%l}. If no date format specifier is given then the following format is used: `Wed Jan 02 02:03:55 1980`. The date format specifier admits the same syntax as the ANSI C function strftime, with 1 addition. The addition is the specifier %l for milliseconds, padded with zeros to make 3 digits.
%m - the message
%n - the platform specific line separator
%p - the level
%r - milliseconds since this layout was created.
%R - seconds since Jan 1, 1970
%u - clock ticks since process start
%x - the NDC
Parameters
conversionPattern the conversion pattern
Exceptions
ConfigureFailure if the pattern is invalid
References clear_conversion_pattern(), std::endl(), and std::ostringstream::str().
Referenced by PatternLayout().
Member Data Documentation
const char * log4tango::PatternLayout::BASIC_CONVERSION_PATTERN = `%R %p %c %m%n` [static]
A conversion pattern equivalent to the BasicLayout.
Referenced by PatternLayout().
The documentation for this class was generated from the following files:
PatternLayout.hh
PatternLayout.cpp