log4tango::LoggerStream Class Reference
#include `LoggerStream.hh`
Public Member Functions
LOG4TANGO_EXPORT LoggerStream (Logger &logger, Level::Value level, bool filter=true)
Construct a LoggerStream for given Logger with given level.
LOG4TANGO_EXPORT ~LoggerStream ()
Destructor for LoggerStream&)
LOG4TANGO_EXPORT void flush (void)
Flush the contents of the stream buffer to the Logger and empties the buffer.
LOG4TANGO_EXPORT Level::Value get_level (void) const
Returns the level for this stream.
LOG4TANGO_EXPORT Logger & get_logger (void) const
Returns the destination Logger for this stream.
LOG4TANGO_EXPORT LoggerStream & operator<< (LOG4TANGO_UNUSED(LogInitiator &i))
Streams in a Initiator.
LOG4TANGO_EXPORT LoggerStream & operator<< (LOG4TANGO_UNUSED(LogSeparator &s))
Streams in a Separator.Sends the contents of the stream buffer to the Logger with set level and empties the buffer.
LOG4TANGO_EXPORT LoggerStream & operator<< (LOG4TANGO_UNUSED(ls_terminator endoflog))
Streams in a ls_manipulator.
LOG4TANGO_EXPORT LoggerStream & operator<< (std::ios_base &(*_F)(std::ios_base &))
Streams in a std stream manipulator.
template<typename T >
LoggerStream & operator<< (const T &t)
Stream in arbitrary types and objects.
Constructor & Destructor Documentation
log4tango::LoggerStream::LoggerStream (Logger & logger, Level::Value level, bool filter = true)
Construct a LoggerStream for given Logger with given level.
Parameters
logger The logger this stream will send log messages to.
level The level the log messages will get or Level::NOTSET to silently discard any streamed in messages.
filter The filter flag
log4tango::LoggerStream::~LoggerStream ()
Destructor for LoggerStream&)
References flush().
Member Function Documentation
void log4tango::LoggerStream::flush (void)
Flush the contents of the stream buffer to the Logger and empties the buffer.
References log4tango::Logger::log(), log4tango::Logger::log_unconditionally(), and std::ostringstream::str().
Referenced by operator<<(), and ~LoggerStream().
LOG4TANGO_EXPORT Level::Value log4tango::LoggerStream::get_level (void) const [inline]
Returns the level for this stream.
Returns
The level.
LOG4TANGO_EXPORT Logger& log4tango::LoggerStream::get_logger (void) const [inline]
Returns the destination Logger for this stream.
Returns
The Logger.
LOG4TANGO_EXPORT LoggerStream& log4tango::LoggerStream::operator<< (LOG4TANGO_UNUSED(LogInitiator &i)) [inline]
Streams in a Initiator.
Just a trick to return a ref to self.
Parameters
i The log initiator
Returns
A reference to itself.
LOG4TANGO_EXPORT LoggerStream& log4tango::LoggerStream::operator<< (LOG4TANGO_UNUSED(LogSeparator &s)) [inline]
Streams in a Separator.Sends the contents of the stream buffer to the Logger with set level and empties the buffer.
Parameters
s The log separator
Returns
A reference to itself.
References flush().
LOG4TANGO_EXPORT LoggerStream& log4tango::LoggerStream::operator<< (LOG4TANGO_UNUSED(ls_terminator endoflog)) [inline]
Streams in a ls_manipulator.
Sends the contents of the stream buffer to the Logger with set level and empties the buffer.
Parameters
endoflog The log terminator
Returns
A reference to itself.
References flush().
LOG4TANGO_EXPORT LoggerStream& log4tango::LoggerStream::operator<< (std::ios_base &(*)(std::ios_base &) _F) [inline]
Streams in a std stream manipulator.
Parameters
_F the manipulator function
Returns
a reference to self.
template<typename T > LoggerStream& log4tango::LoggerStream::operator<< (const T & t) [inline]
Stream in arbitrary types and objects.
Parameters
t The value or object to stream in.
Returns
A reference to itself.
References log4tango::Level::OFF.
The documentation for this class was generated from the following files:
LoggerStream.hh
LoggerStream.cpp