Tango::TemplCommandInOut< INARG, OUTARG > Class Template Reference
This class is a class representing a command in the template command model with output and input parameters.
Public Member Functions
~TemplCommandInOut ()
Constructors
Miscellaneous constructors
TemplCommandInOut (const char *cmd_name, OUTARG(DeviceImpl::*exe_method)(INARG))
Constructs a newly allocated TemplCommandInOut object for a command with a name and an execution method.
TemplCommandInOut (string &cmd_name, OUTARG(DeviceImpl::*exe_method)(INARG))
Constructs a newly allocated TemplCommandInOut object for a command with a name and an execution method.
TemplCommandInOut (const char *cmd_name, OUTARG(DeviceImpl::*exe_method)(INARG), bool(DeviceImpl::*state_method)(const CORBA::Any &))
Constructs a newly allocated TemplCommandInout object for a command with a name, an execution method and a command allowed method.
TemplCommandInOut (string &cmd_name, OUTARG(DeviceImpl::*exe_method)(INARG), bool(DeviceImpl::*state_method)(const CORBA::Any &))
Constructs a newly allocated TemplCommandInOut object for a command with a name, an execution method and a command allowed method.
TemplCommandInOut (const char *cmd_name, OUTARG(DeviceImpl::*exe_method)(INARG), const char *in_desc, const char *out_desc)
Constructs a newly allocated TemplCommandInOut object for a command with a name, an execution method and a description for the input and output command parameters.
TemplCommandInOut (string &cmd_name, OUTARG(DeviceImpl::*exe_method)(INARG), string &in_desc, string &out_desc)
Constructs a newly allocated TemplCommandInOut object for a command with a name, an execution method and a description for the input and output command parameters.
TemplCommandInOut (const char *cmd_name, OUTARG(DeviceImpl::*exe_method)(INARG), bool(DeviceImpl::*state_method)(const CORBA::Any &), const char *in_desc, const char *out_desc)
Constructs a newly allocated TemplCommandInOut object for a command with a name, an execution method, a command allowed method and a description for the input and output command parameters.
TemplCommandInOut (string &cmd_name, OUTARG(DeviceImpl::*exe_method)(INARG), bool(DeviceImpl::*state_method)(const CORBA::Any &), string &in_desc, string &out_desc)
Constructs a newly allocated TemplCommandInOut object for a command with a name, an execution method, a command allowed method and a description for the input and output command parameters.
TemplCommandInOut (const char *cmd_name, OUTARG(DeviceImpl::*exe_method)(INARG), Tango::DispLevel level)
Constructs a newly allocated TemplCommandInOut object for a command with a name and an execution method.
TemplCommandInOut (string &cmd_name, OUTARG(DeviceImpl::*exe_method)(INARG), Tango::DispLevel level)
Constructs a newly allocated TemplCommandInOut object for a command with a name and an execution method.
TemplCommandInOut (const char *cmd_name, OUTARG(DeviceImpl::*exe_method)(INARG), bool(DeviceImpl::*state_method)(const CORBA::Any &), Tango::DispLevel level)
Constructs a newly allocated TemplCommandInout object for a command with a name, an execution method and a command allowed method.
TemplCommandInOut (string &cmd_name, OUTARG(DeviceImpl::*exe_method)(INARG), bool(DeviceImpl::*state_method)(const CORBA::Any &), Tango::DispLevel level)
Constructs a newly allocated TemplCommandInOut object for a command with a name, an execution method and a command allowed method.
TemplCommandInOut (const char *cmd_name, OUTARG(DeviceImpl::*exe_method)(INARG), const char *in_desc, const char *out_desc, Tango::DispLevel level)
Constructs a newly allocated TemplCommandInOut object for a command with a name, an execution method and a description for the input and output command parameters.
TemplCommandInOut (string &cmd_name, OUTARG(DeviceImpl::*exe_method)(INARG), string &in_desc, string &out_desc, Tango::DispLevel level)
Constructs a newly allocated TemplCommandInOut object for a command with a name, an execution method and a description for the input and output command parameters.
TemplCommandInOut (const char *cmd_name, OUTARG(DeviceImpl::*exe_method)(INARG), bool(DeviceImpl::*state_method)(const CORBA::Any &), const char *in_desc, const char *out_desc, Tango::DispLevel level)
Constructs a newly allocated TemplCommandInOut object for a command with a name, an execution method, a command allowed method and a description for the input and output command parameters.
TemplCommandInOut (string &cmd_name, OUTARG(DeviceImpl::*exe_method)(INARG), bool(DeviceImpl::*state_method)(const CORBA::Any &), string &in_desc, string &out_desc, Tango::DispLevel level)
Constructs a newly allocated TemplCommandInOut object for a command with a name, an execution method, a command allowed method and a description for the input and output command parameters.
Miscellaneous methods
void init_types ()
Initialise command input and output types.
CORBA::Any * execute (DeviceImpl *dev, const CORBA::Any &in_any)
Invoke the command execution method given at object creation time.
Additional Inherited Members
Detailed Description
template<typename INARG, typename OUTARG>class Tango::TemplCommandInOut< INARG, OUTARG >
This class is a class representing a command in the template command model with output and input parameters.
The class template parameters (called INARG and OUTARG) are the command input parameter type and the command output parameter type.
Synopsis : template <typename INARG,typename OUTARG> class TemplCommandInOut:public TemplCommand;
Usage : new TemplCommandInOut<Tango::DevLong,Tango::DevFloat>(...);
$Author$ $Revision$
Constructor & Destructor Documentation
template<typename INARG , typename OUTARG > Tango::TemplCommandInOut< INARG, OUTARG >::TemplCommandInOut (const char * cmd_name, OUTARG(DeviceImpl::*)(INARG) exe_method)
Constructs a newly allocated TemplCommandInOut object for a command with a name and an execution method.
The input and output command data type are automatically determined. The input and output parameter description are set to the default String `Uninitialised`. The command display level is set to OPERATOR.
Parameters
cmd_name The command name
exe_method Pointer to the command execution method
References Tango::TemplCommand::allowed_ptr, and Tango::TemplCommandInOut< INARG, OUTARG >::init_types().
template<typename INARG , typename OUTARG > Tango::TemplCommandInOut< INARG, OUTARG >::TemplCommandInOut (string & cmd_name, OUTARG(DeviceImpl::*)(INARG) exe_method)
Constructs a newly allocated TemplCommandInOut object for a command with a name and an execution method.
The input and output command data type are automatically determined. The input and output parameter description are set to the default String `Uninitialised`. The command display level is set to OPERATOR.
Parameters
cmd_name The command name
exe_method Pointer to the command execution method
References Tango::TemplCommand::allowed_ptr, and Tango::TemplCommandInOut< INARG, OUTARG >::init_types().
template<typename INARG , typename OUTARG > Tango::TemplCommandInOut< INARG, OUTARG >::TemplCommandInOut (const char * cmd_name, OUTARG(DeviceImpl::*)(INARG) exe_method, bool(DeviceImpl::*)(const CORBA::Any &) state_method)
Constructs a newly allocated TemplCommandInout object for a command with a name, an execution method and a command allowed method.
The input and output command data type are automatically determined. The input and output parameter description are set to the default String `Uninitialised`. The command display level is set to OPERATOR.
Parameters
cmd_name The command name
exe_method Pointer to the command execution method
state_method Pointer to the command allowed method
References Tango::TemplCommand::allowed_ptr, and Tango::TemplCommandInOut< INARG, OUTARG >::init_types().
template<typename INARG , typename OUTARG > Tango::TemplCommandInOut< INARG, OUTARG >::TemplCommandInOut (string & cmd_name, OUTARG(DeviceImpl::*)(INARG) exe_method, bool(DeviceImpl::*)(const CORBA::Any &) state_method)
Constructs a newly allocated TemplCommandInOut object for a command with a name, an execution method and a command allowed method.
The input and output command data type are automatically determined. The input and output parameter description are set to the default String `Uninitialised`. The command display level is set to OPERATOR.
Parameters
cmd_name The command name
exe_method Pointer to the command execution method
state_method Pointer to the command allowed method
References Tango::TemplCommand::allowed_ptr, and Tango::TemplCommandInOut< INARG, OUTARG >::init_types().
template<typename INARG , typename OUTARG > Tango::TemplCommandInOut< INARG, OUTARG >::TemplCommandInOut (const char * cmd_name, OUTARG(DeviceImpl::*)(INARG) exe_method, const char * in_desc, const char * out_desc)
Constructs a newly allocated TemplCommandInOut object for a command with a name, an execution method and a description for the input and output command parameters.
The input and output command data type are automatically determined. The command display level is set to OPERATOR.
Parameters
cmd_name The command name
exe_method Pointer to the command execution method
in_desc The command input parameter description
out_desc The command output parameter description
References Tango::TemplCommand::allowed_ptr, and Tango::TemplCommandInOut< INARG, OUTARG >::init_types().
template<typename INARG , typename OUTARG > Tango::TemplCommandInOut< INARG, OUTARG >::TemplCommandInOut (string & cmd_name, OUTARG(DeviceImpl::*)(INARG) exe_method, string & in_desc, string & out_desc)
Constructs a newly allocated TemplCommandInOut object for a command with a name, an execution method and a description for the input and output command parameters.
The input and output command data type are automatically determined. The command display level is set to OPERATOR.
Parameters
cmd_name The command name
exe_method Pointer to the command execution method
in_desc The command input parameter description
out_desc The command output parameter description
References Tango::TemplCommand::allowed_ptr, and Tango::TemplCommandInOut< INARG, OUTARG >::init_types().
template<typename INARG , typename OUTARG > Tango::TemplCommandInOut< INARG, OUTARG >::TemplCommandInOut (const char * cmd_name, OUTARG(DeviceImpl::*)(INARG) exe_method, bool(DeviceImpl::*)(const CORBA::Any &) state_method, const char * in_desc, const char * out_desc)
Constructs a newly allocated TemplCommandInOut object for a command with a name, an execution method, a command allowed method and a description for the input and output command parameters.
The input and output command data type are automatically determined. The command display level is set to OPERATOR.
Parameters
cmd_name The command name
exe_method Pointer to the command execution method
state_method Pointer to the command allowed method
in_desc The command input parameter description
out_desc The command output parameter description
References Tango::TemplCommand::allowed_ptr, and Tango::TemplCommandInOut< INARG, OUTARG >::init_types().
template<typename INARG , typename OUTARG > Tango::TemplCommandInOut< INARG, OUTARG >::TemplCommandInOut (string & cmd_name, OUTARG(DeviceImpl::*)(INARG) exe_method, bool(DeviceImpl::*)(const CORBA::Any &) state_method, string & in_desc, string & out_desc)
Constructs a newly allocated TemplCommandInOut object for a command with a name, an execution method, a command allowed method and a description for the input and output command parameters.
The input and output command data type are automatically determined. The command display level is set to OPERATOR.
Parameters
cmd_name The command name
exe_method Pointer to the command execution method
state_method Pointer to the command allowed method
in_desc The command input parameter description
out_desc The command output parameter description
References Tango::TemplCommand::allowed_ptr, and Tango::TemplCommandInOut< INARG, OUTARG >::init_types().
template<typename INARG , typename OUTARG > Tango::TemplCommandInOut< INARG, OUTARG >::TemplCommandInOut (const char * cmd_name, OUTARG(DeviceImpl::*)(INARG) exe_method, Tango::DispLevel level)
Constructs a newly allocated TemplCommandInOut object for a command with a name and an execution method.
The input and output command data type are automatically determined. The input and output parameter description are set to the default String `Uninitialised`.
Parameters
cmd_name The command name
exe_method Pointer to the command execution method
level The command display level
References Tango::TemplCommand::allowed_ptr, and Tango::TemplCommandInOut< INARG, OUTARG >::init_types().
template<typename INARG , typename OUTARG > Tango::TemplCommandInOut< INARG, OUTARG >::TemplCommandInOut (string & cmd_name, OUTARG(DeviceImpl::*)(INARG) exe_method, Tango::DispLevel level)
Constructs a newly allocated TemplCommandInOut object for a command with a name and an execution method.
The input and output command data type are automatically determined. The input and output parameter description are set to the default String `Uninitialised`.
Parameters
cmd_name The command name
exe_method Pointer to the command execution method
level The command display level
References Tango::TemplCommand::allowed_ptr, and Tango::TemplCommandInOut< INARG, OUTARG >::init_types().
template<typename INARG , typename OUTARG > Tango::TemplCommandInOut< INARG, OUTARG >::TemplCommandInOut (const char * cmd_name, OUTARG(DeviceImpl::*)(INARG) exe_method, bool(DeviceImpl::*)(const CORBA::Any &) state_method, Tango::DispLevel level)
Constructs a newly allocated TemplCommandInout object for a command with a name, an execution method and a command allowed method.
The input and output command data type are automatically determined. The input and output parameter description are set to the default String `Uninitialised`.
Parameters
cmd_name The command name
exe_method Pointer to the command execution method
state_method Pointer to the command allowed method
level The command display level
References Tango::TemplCommand::allowed_ptr, and Tango::TemplCommandInOut< INARG, OUTARG >::init_types().
template<typename INARG , typename OUTARG > Tango::TemplCommandInOut< INARG, OUTARG >::TemplCommandInOut (string & cmd_name, OUTARG(DeviceImpl::*)(INARG) exe_method, bool(DeviceImpl::*)(const CORBA::Any &) state_method, Tango::DispLevel level)
Constructs a newly allocated TemplCommandInOut object for a command with a name, an execution method and a command allowed method.
The input and output command data type are automatically determined. The input and output parameter description are set to the default String `Uninitialised`.
Parameters
cmd_name The command name
exe_method Pointer to the command execution method
state_method Pointer to the command allowed method
level The command display level
References Tango::TemplCommand::allowed_ptr, and Tango::TemplCommandInOut< INARG, OUTARG >::init_types().
template<typename INARG , typename OUTARG > Tango::TemplCommandInOut< INARG, OUTARG >::TemplCommandInOut (const char * cmd_name, OUTARG(DeviceImpl::*)(INARG) exe_method, const char * in_desc, const char * out_desc, Tango::DispLevel level)
Constructs a newly allocated TemplCommandInOut object for a command with a name, an execution method and a description for the input and output command parameters.
The input and output command data type are automatically determined.
Parameters
cmd_name The command name
exe_method Pointer to the command execution method
in_desc The command input parameter description
out_desc The command output parameter description
level The command display level
References Tango::TemplCommand::allowed_ptr, and Tango::TemplCommandInOut< INARG, OUTARG >::init_types().
template<typename INARG , typename OUTARG > Tango::TemplCommandInOut< INARG, OUTARG >::TemplCommandInOut (string & cmd_name, OUTARG(DeviceImpl::*)(INARG) exe_method, string & in_desc, string & out_desc, Tango::DispLevel level)
Constructs a newly allocated TemplCommandInOut object for a command with a name, an execution method and a description for the input and output command parameters.
The input and output command data type are automatically determined.
Parameters
cmd_name The command name
exe_method Pointer to the command execution method
in_desc The command input parameter description
out_desc The command output parameter description
level The command display level
References Tango::TemplCommand::allowed_ptr, and Tango::TemplCommandInOut< INARG, OUTARG >::init_types().
template<typename INARG , typename OUTARG > Tango::TemplCommandInOut< INARG, OUTARG >::TemplCommandInOut (const char * cmd_name, OUTARG(DeviceImpl::*)(INARG) exe_method, bool(DeviceImpl::*)(const CORBA::Any &) state_method, const char * in_desc, const char * out_desc, Tango::DispLevel level)
Constructs a newly allocated TemplCommandInOut object for a command with a name, an execution method, a command allowed method and a description for the input and output command parameters.
The input and output command data type are automatically determined.
Parameters
cmd_name The command name
exe_method Pointer to the command execution method
state_method Pointer to the command allowed method
in_desc The command input parameter description
out_desc The command output parameter description
level The command display level
References Tango::TemplCommand::allowed_ptr, and Tango::TemplCommandInOut< INARG, OUTARG >::init_types().
template<typename INARG , typename OUTARG > Tango::TemplCommandInOut< INARG, OUTARG >::TemplCommandInOut (string & cmd_name, OUTARG(DeviceImpl::*)(INARG) exe_method, bool(DeviceImpl::*)(const CORBA::Any &) state_method, string & in_desc, string & out_desc, Tango::DispLevel level)
Constructs a newly allocated TemplCommandInOut object for a command with a name, an execution method, a command allowed method and a description for the input and output command parameters.
The input and output command data type are automatically determined.
Parameters
cmd_name The command name
exe_method Pointer to the command execution method
state_method Pointer to the command allowed method
in_desc The command input parameter description
out_desc The command output parameter description
level The command display level
References Tango::TemplCommand::allowed_ptr, and Tango::TemplCommandInOut< INARG, OUTARG >::init_types().
template<typename INARG , typename OUTARG > Tango::TemplCommandInOut< INARG, OUTARG >::~TemplCommandInOut () [inline]
Member Function Documentation
template<typename INARG , typename OUTARG > CORBA::Any * Tango::TemplCommandInOut< INARG, OUTARG >::execute (DeviceImpl * dev, const CORBA::Any & in_any) [virtual]
Invoke the command execution method given at object creation time.
This method is automtically called by the TANGO core classes when the associated command is requested by a client. It first unpacks the incoming data. Then, it invokes the user supplied command execution method and packs the returned data into the outgoing CORBA Any object
Parameters
dev The device on which the command must be executed
in_any The incoming data still packed in a CORBA Any object.
Returns
The CORBA Any object returned to the client.
Exceptions
DevFailed If the execution method failed Click here to read DevFailed exception specification
Reimplemented from Tango::TemplCommand .
template<typename INARG , typename OUTARG > void Tango::TemplCommandInOut< INARG, OUTARG >::init_types () [virtual]
Initialise command input and output types.
Set the command output type to Tango::DEV_VOID. The command input type is automatically determined from the class template specialisation
Reimplemented from Tango::Command .
Referenced by Tango::TemplCommandInOut< INARG, OUTARG >::TemplCommandInOut().
The documentation for this class was generated from the following file:
command.h