log4tango::Level Class Reference
#include `Level.hh`
Public Types
enum LevelLevel {
*
OFF = 100,
*
FATAL = 200,
*
ERROR = 300,
*
WARN = 400,
*
INFO = 500,
*
DEBUG = 600
 }
Levels of Priorities.
typedef int Value
The type of Level Values.
Static Public Member Functions
static const std::string & get_name (Value level)
Returns the name of the given level value.
static Value get_value (const std::string &level_name) throw (std::invalid_argument)
Returns the value of the given level name.
Member Typedef Documentation
typedef int log4tango::Level::Value
The type of Level Values.
Member Enumeration Documentation
enum log4tango::Level::LevelLevel
Levels of Priorities.
Enumerator
OFF
FATAL
ERROR
WARN
INFO
DEBUG
Member Function Documentation
const std::string & log4tango::Level::get_name (Value level) [static]
Returns the name of the given level value.
Currently, if the value is not one of the LevelLevel values, the method returns the name of the largest level smaller the given value.
Parameters
level the numeric value of the level.
Returns
a string representing the name of the level.
References NUM_LEVELS.
Referenced by log4tango::LevelComponent::append(), log4tango::XMLLayout::format(), and log4tango::Layout::format().
Level::Value log4tango::Level::get_value (const std::string & level_name) throw std::invalid_argument) [static]
Returns the value of the given level name.
This can be either one of `OFF`, `ERRROR`, ... or a decimal string representation of the value, e.g. '500' for DEBUG.
Parameters
level_name the string containing the the of the level
Returns
the value corresponding with the level name
Exceptions
std::invalid_argument if the level_name does not correspond with a known Level name or a number
References NUM_LEVELS.
The documentation for this class was generated from the following files:
Level.hh
Level.cpp