log4tango::RollingFileAppender Class Reference
#include `RollingFileAppender.hh`
Public Member Functions
RollingFileAppender (const std::string &name, const std::string &file_name, size_t max_fs=10 *1024 *1024, unsigned int max_bi=1, bool append=true, mode_t mode=00644)
virtual unsigned int get_max_backup_index () const
virtual size_t get_max_file_size () const
virtual void roll_over ()
virtual void set_max_backup_index (unsigned int maxBackups)
virtual void set_maximum_file_size (size_t max_fs)
Protected Member Functions
virtual int _append (const LoggingEvent &event)
Log in Appender specific way.
Protected Attributes
unsigned int _max_backup_index
size_t _max_file_size
Additional Inherited Members
Constructor & Destructor Documentation
log4tango::RollingFileAppender::RollingFileAppender (const std::string & name, const std::string & file_name, size_t max_fs = 10*1024*1024, unsigned int max_bi = 1, bool append = true, mode_t mode = 00644)
Member Function Documentation
int log4tango::RollingFileAppender::_append (const LoggingEvent & event) [protected], [virtual]
Log in Appender specific way.
Subclasses of Appender should implement this method to perform actual logging.
Parameters
event The LoggingEvent to log.
Reimplemented from log4tango::FileAppender .
References log4tango::FileAppender::_append(), log4tango::FileAppender::_fd, _max_file_size, and roll_over().
unsigned int log4tango::RollingFileAppender::get_max_backup_index () const [virtual]
References _max_backup_index.
size_t log4tango::RollingFileAppender::get_max_file_size () const [virtual]
References _max_file_size.
void log4tango::RollingFileAppender::roll_over () [virtual]
References log4tango::FileAppender::_fd, log4tango::FileAppender::_file_name, log4tango::FileAppender::_flags, _max_backup_index, log4tango::FileAppender::_mode, log4tango::FileAppender::close(), and std::ostringstream::str().
Referenced by _append().
void log4tango::RollingFileAppender::set_max_backup_index (unsigned int maxBackups) [virtual]
References _max_backup_index.
void log4tango::RollingFileAppender::set_maximum_file_size (size_t max_fs) [virtual]
References _max_file_size.
Member Data Documentation
unsigned int log4tango::RollingFileAppender::_max_backup_index [protected]
Referenced by get_max_backup_index(), roll_over(), and set_max_backup_index().
size_t log4tango::RollingFileAppender::_max_file_size [protected]
Referenced by _append(), get_max_file_size(), and set_maximum_file_size().
The documentation for this class was generated from the following files:
RollingFileAppender.hh
RollingFileAppender.cpp