void MyClass::init_device()
{
    ...
    ...
    Tango::Attribute &att = dev_attr->get_attr_by_name("TheAttribute");
    att.set_attr_serial_model(Tango::ATTR_BY_USER);
    ....
    ....
    
}


void MyClass::read_TheAttribute(Tango::Attribute &attr)
{
    ....
    ....
    the_mutex.lock();
    ....
// Fill the attribute buffer
    ....
    attr.set_value(buffer,....);
    attr->set_user_attr_mutex(&the_mutex);
}

